export { AcercaDe } from './sections/AcercaDe';
export { Habilidades } from './sections/Habilidades';
export { Proyectos } from './sections/Proyectos';
export { Contact } from './contacto/Contact';
export { Footer } from './footer/Footer';
export { Hero } from './hero/Hero';
export { Navbar } from './navbar/Navbar';
export { ScrollIndicator } from './ScrollIndicator';
export { Legal } from './legal/Legal';
